version: '3.7'

services:

  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - .env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  app:
    build: .
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=online_assessment.settings

volumes:
  database-data: # named volumes can be managed easier using docker-compose
  online_assessment: